GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYW5hbnRoIiwiaWF0IjoxNTY5MTY5MDExfQ.fqbu0gLGMzulMo6ypVtBFhVhEouWbQ7Erm3tGtGCXv4

###

POST  http://localhost:3000/login
Content-type: application/json

{
    "username":"ananth"
}