GET http://localhost:8888/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoia2FubmFuIiwiaWF0IjoxNTY5MzA4NjYwLCJleHAiOjE1NjkzMDg2OTB9.cx95pSc3IXM1RGJ2VO9eWnLS6d7bUZqHyMCWKO9qPWI

###

POST  http://localhost:8888/login
Content-type: application/json

{
    "username":"kannan"
}
###

POST http://localhost:8888/token_gen_using_referesh_token
Content-type: application/json

{
    "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoia2FubmFuIiwiaWF0IjoxNTY5MzA5MTQ4fQ.uYuaE7WTtnG5B43QPiY446S-pZxumc1Z1ALCGH9_T20" 
}
###

POST http://localhost:8888/logout
Content-type: application/json

{
    "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoia2FubmFuIiwiaWF0IjoxNTY5MzA5MTQ4fQ.uYuaE7WTtnG5B43QPiY446S-pZxumc1Z1ALCGH9_T20" 
}
